# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
registries:
  nuget-org:
    type: nuget-feed
    url: "https://api.nuget.org/v3/index.json"
  nuget-roofstock-devops:
    type: nuget-feed
    url: https://pkgs.dev.azure.com/Roofstock/_packaging/LocalPackages/nuget/v3/index.json
    username: "Roofstock" # this is the Azure DevOps organization name
    password: ${{secrets.AZURE_DEVOPS_PACKAGES_READER_PASSWORD}} # this is the non-base64 encoded PAT
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/" # Location of package manifests
    rebase-strategy: "disabled" # Disable rebasing for pull requests
    registries:
      - nuget-org
      - nuget-roofstock-devops
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "EPPlus"  
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      core-nuget:
        dependency-type: "production" # Exclude Pre-release versions
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "Azure*"
          - "AutoMapper*"
          - "Bogus*"
          - "bunit*"
          - "Dapper*"
          - "EFCore*"
          - "FakeItEasy*"
          - "FluentValidation*"
          - "Grpc*"
          - "MediatR*"
          - "Microsoft*"
          - "Roofstock*"
          - "Serilog*"
          - "Shouldly*"
          - "Snowflake*"
          - "System*"
          - "xunit*"
      other-nuget:
        dependency-type: "production" # Exclude Pre-release versions
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
        exclude-patterns:
          - "Azure*"
          - "AutoMapper*"
          - "Bogus*"
          - "bunit*"
          - "Dapper*"
          - "EFCore*"
          - "FakeItEasy*"
          - "FluentValidation*"
          - "Grpc*"
          - "MediatR*"
          - "Microsoft*"
          - "Roofstock*"
          - "Serilog*"
          - "Shouldly*"
          - "Snowflake*"
          - "System*"
          - "xunit*"
