name: auto-merge

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      # Checkout all branches to be use by task below
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: List branches
        run: |
          git branch -a

      - name: Create and merge pull request
        shell: pwsh
        run: |
          .github/workflows/src/auto-merge/auto-merge.ps1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
